Repository DedSecInside/TorBot, pull requests merged in 2018-03, with the labels that each got.

#69 Title feature added
  modules/getweblinks.py
  modules/info.py
  modules/pagereader.py
  tests/test_getemails.py
  tests/test_getweblinks.py
  torBot.py
Labels: LOW PRIORITY, NEW FEATURE, TO REVIEW

#74 Added new http requests mock for pagereader test
  requirements.txt
  tests/test_pagereader.py
Labels: MED PRIORITY, TO MERGE, UNITTEST

#80 Made Schema optional for more robust choices url
  modules/getweblinks.py
  modules/pagereader.py
  tests/test_pagereader.py
  torBot.py
Labels: ENHANCEMENT, LOW PRIORITY, MERGE APPROVED

#76 Page description function added
  modules/info.py
Labels: MED PRIORITY, MERGE APPROVED, NEW FEATURE
