Repository DedSecInside/TorBot, pull requests merged in 2018-10, with the labels that each got.

#128 Typo in Readme
  README.md
Labels: DOC, HACKTOBERFEST, TRIVAL FIX

#133 Fix cprints by adding commas separating text and color parameters
  modules/info.py
Labels: BUG, HACKTOBERFEST, TO REVIEW, TRIVAL FIX

#134 Update CHANGELOG.md
  CHANGELOG.md
Labels: CHANGELOG, ENHANCEMENT, GOOD FIRST ISSUE, HACKTOBERFEST, LOW PRIORITY, MERGE APPROVED, TRIVAL FIX

#125 Correctly generating tree, tree visuals and refactoring
  .travis.yml
  modules/analyzer.py
  modules/color.py
  modules/colors.py
  modules/getemails.py
  modules/getweblinks.py
  modules/info.py
  modules/pagereader.py
  modules/tests/TESTING.md
  modules/tests/__init__.py
  modules/tests/test_getemails.py
  modules/tests/test_getweblinks.py
  modules/tests/test_pagereader.py
  modules/tests/test_savetofile.py
  modules/utils.py
  requirements.txt
  torBot.py
Labels: HACKTOBERFEST, MAJOR UPGRADE, MED PRIORITY, NEW FEATURE, READY TO MERGE

#139 Major Refactoring
  .DS_Store
  CHANGELOG.md
  install.sh
  modules/analyzer.py
  modules/color.py
  modules/getemails.py
  modules/getweblinks.py
  modules/go_linker.py
  modules/info.py
  modules/lib/build.sh
  modules/lib/go_dep.sh
  modules/lib/go_get_urls.go
  modules/lib/go_get_urls.h
  modules/lib/go_get_urls_test.go
  modules/link.py
  modules/link_io.py
  modules/pagereader.py
  modules/tests/test_analyzer.py
  modules/tests/test_getemails.py
  modules/tests/test_getweblinks.py
  modules/tests/test_pagereader.py
  requirements.txt
  torBot.py
Labels: ENHANCEMENT, HACKTOBERFEST, MAJOR UPGRADE, PERFORMANCE, READY TO MERGE

#144 Using multi-threading for tree generation with links and adding documentation
  modules/analyzer.py
  modules/link.py
  modules/link_io.py
  modules/tests/test_getweblinks.py
  modules/utils.py
  torBot.py
Labels: ENHANCEMENT, HACKTOBERFEST, MAJOR UPGRADE, MERGE APPROVED, NEW FEATURE, PERFORMANCE

#135 Add .gitattributes file
  .gitattributes
Labels: GOOD FIRST ISSUE, HACKTOBERFEST, LOW PRIORITY, MERGE APPROVED

#147 Update README.md
  README.md
Labels: DOC, ENHANCEMENT, GOOD FIRST ISSUE, HACKTOBERFEST, MERGE APPROVED, TRIVAL FIX

#149 Updating requests version
  requirements.txt
Labels: CRITICAL, SECURITY PATCH
