Repository DedSecInside/TorBot, pull requests merged in 2018-08, with the labels that each got.

#108 Adding get_args
  torBot.py
Labels: BUG, CRITICAL, MERGE APPROVED

#75 Feature db
  .env
  __pycache__/settings.cpython-36.pyc
  modules/savedb.py
  settings.py
  torBot.py
Labels: MED PRIORITY, NEW FEATURE, ON GOING, TO REVIEW

#112 Adding more test coverage
  tests/test_getemails.py
  tests/test_getweblinks.py
Labels: ENHANCEMENT, UNITTEST

#111 Add function to traverse links using Breadth First Search
  modules/getweblinks.py
Labels: ENHANCEMENT, MAJOR UPGRADE, MERGE APPROVED, NEW FEATURE, URGENT

#114 Updated Req.txt
  .gitignore
  FAQ.md
  __pycache__/settings.cpython-36.pyc
  modules/savedb.py
  requirements.txt
Labels: LOW PRIORITY, MERGE APPROVED, TRIVAL FIX
