Repository DedSecInside/TorBot, pull requests merged in 2018-07, with the labels that each got.

#96 Pep8. Whitespace. Fixed raised string error
  modules/getemails.py
  modules/getweblinks.py
  modules/pagereader.py
  tests/test_getemails.py
  tests/test_getweblinks.py
  tests/test_savetofile.py
  torBot.py
Labels: FIXED, GOOD FIRST ISSUE, ISSUE FIXED, MERGE APPROVED

#95 Refactored tests and TorBot app so that tests no longer need to touch
  .gitignore
  modules/getemails.py
  modules/getweblinks.py
  modules/net_utils.py
  modules/pagereader.py
  requirements.txt
  tests/test_getemails.py
  tests/test_getweblinks.py
  tests/test_pagereader.py
  torBot.py
Labels: ON GOING, UNITTEST

#99 Adding configurable ip and port arguments
  torBot.py
Labels: ENHANCEMENT, LOW PRIORITY, MERGE APPROVED, NEW FEATURE, PEP8

#101 Formatted .gitignore file and added __init__to modules dir
  .gitignore
  modules/__init__.py
Labels: ENHANCEMENT, LOW PRIORITY, MERGE APPROVED

#103 Feature pep8
  modules/getemails.py
  modules/getweblinks.py
  modules/net_utils.py
  modules/pagereader.py
  torBot.py
Labels: ENHANCEMENT, GOOD FIRST ISSUE, MERGE APPROVED, PEP8

#105 New Templates when someone is trying to edit the project
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/pull-request.md
Labels: DOC, ENHANCEMENT, MERGE APPROVED
