Repository DedSecInside/TorBot, pull requests merged in 2019-10, with the labels that each got.

#165 Add doc strings for functions.
  modules/updater.py
Labels: DOC, ENHANCEMENT, HACKTOBERFEST

#167 Dockerize torbot
  Dockerfile
  README.md
Labels: ENHANCEMENT, HACKTOBERFEST, TO REVIEW

#168 Save response headers as metadata.
  modules/link.py
Labels: GOOD FIRST ISSUE, HACKTOBERFEST, MED PRIORITY, TO MERGE

#162 Collect data | Machine Learning Phase I
  data/torbot_2019-05-29T17:07:19.146583.csv
  modules/collect_data.py
  modules/utils.py
  requirements.txt
  torBot.py
  torbot_dev.env
Labels: MACHINE LEARNING, NEW FEATURE, READY TO MERGE

#169 Add and Update Documentation
  modules/analyzer.py
  modules/collect_data.py
  modules/color.py
  modules/info.py
  modules/link.py
  modules/link_io.py
  modules/savefile.py
  modules/tests/test_analyzer.py
  modules/updater.py
  modules/utils.py
  torBot.py
Labels: DOC, GOOD FIRST ISSUE, HACKTOBERFEST, READY TO MERGE

#170 Refactor analyzer
  modules/analyzer.py
  modules/tests/test_analyzer.py
  modules/tests/test_getweblinks.py
  modules/tests/test_pagereader.py
Labels: ENHANCEMENT, ISSUE FIXED, MERGE APPROVED

#172 Code style
  modules/analyzer.py
  modules/collect_data.py
  modules/color.py
  modules/info.py
  modules/link_io.py
  modules/utils.py
Labels: ENHANCEMENT, GOOD FIRST ISSUE, HACKTOBERFEST, MERGE APPROVED, PEP8
